#define UI_TYPE_BUTTON 0
#define UI_TYPE_TEXTBOX 1
#define UI_TYPE_WIDGET 2
#define UI_TYPE_CHECKBOX 3
#define UI_TYPE_TABWIDGET 4
#define UI_TYPE_TEXTWIDGET 5
#define UI_TYPE_COMBOBOX 6
#define UI_TYPE_IMAGEBOX 7